### ISSUE TITLE
dimensions of _av_ type cluster information in ONE_format

### ISSUE THREAD

**Issue by takacsflora** [cortex-lab/PinkRigs#16]

**Comment by pipcoen** [comment]
Just to be sure. This requires rerunning the video alignment, right? @takacsflora @cbimbo?

**Comment by pipcoen** [comment]
Just to be sure. This requires rerunning spike extraction, right? @takacsflora @cbimbo?

**Comment by takacsflora** [comment]
yes

**Comment by takacsflora** [comment]
.. making more changes on this front: the ibl qmetrics rows did not match other clusters raws, as qMetrics are not computed on v trash units, making nClusters inconsistent across clusters' attributes. So I changed the _av_qMetrics.pqt to insert empty rows.
