### ISSUE TITLE
when there is no data in exp2checklist, preprocessing calls some recordings automatically 

### ISSUE THREAD

**Issue by takacsflora** [cortex-lab/PinkRigs#18]
MWE: (point is, there is no such session).
```
params.subject = {'FT010'};
params.expDate = {'2021-01-20'};
params.expNum = '8';

exp2checkList = csv.queryExp(params);
 
preproc.extractExpData(exp2checkList,'recompute',{'spikes'},'KSversion','KS2');
```
a bunch of AV015 and AV021 was attempted to be processed: 
![image](https://user-images.githubusercontent.com/40361594/192174457-7f183610-e217-44e0-8482-890110f17ba0.png)

**Comment by cbimbo** [comment]
That's because when `exp2checkList ` is empty the default subjects get assigned. That was a tricky one to fix, I think I did (mainly modifying `csv.inputValidation`) but it may not be the most elegant. @pipcoen feel free to take a look and modify if you find a smoother way. Thanks!

**Comment by pipcoen** [comment]
Seems fine to me
