### ISSUE TITLE
Data transfer crashing on ephys4

### ISSUE THREAD

**Issue by cbimbo** [cortex-lab/PinkRigs#21]

**Comment by takacsflora** [comment]
same on ephys 3:, error seems to be with csvs: 
![image](https://user-images.githubusercontent.com/40361594/195292590-e3c28ebe-90a2-48dd-b8cb-9d35749f9140.png)

**Comment by takacsflora** [comment]
Note: I thought it had something to do with AV015 not having an explant date in the csv, so I added a random one (did not fix the issue)

**Comment by cbimbo** [comment]
It was because the 'checkProbeUse' was loading all subjects for that probe.
