### ISSUE TITLE
queryCSV errors when no files match condition

### ISSUE THREAD

**Issue by Timothysit** [cortex-lab/PinkRigs#22]
In the queryCSV function here:

https://github.com/cortex-lab/PinkRigs/blob/1d77f021930fca839120238ee02202005e6835c1/Analysis/helpers/queryExp.py

if `exp2checkList` is empty, then the line 

`exp2checkList = pd.concat(exp2checkList)` errors, eg. if I call this function from run_facemapy.py to look for the last10 active mice and there are no active mice, then it crashes. It will be good to have it return an empty dataframe or None so the downstream code can deal with it. 

Thanks!

**Comment by takacsflora** [comment]
thanks for flagging this up, should be fixed now
