### ISSUE TITLE
Path error on the ibl processing stuff

### ISSUE THREAD

**Issue by pipcoen** [cortex-lab/PinkRigs#23]
From Kilo 1:
FileNotFoundError: [Errno 2] No such file or directory: '\\\\[zserver.cortexlab.net](http://zserver.cortexlab.net/)\\Code\\AVrig\\Helpers\\ibl_formatting_queue.

**Comment by takacsflora** [comment]
Admin/csv_pyhandler.py for further global csv handling in python
