### ISSUE TITLE
ephys alignment issue 

### ISSUE THREAD

**Issue by takacsflora** [cortex-lab/PinkRigs#26]
Experiment 
`zaru\AV024\2022-10-11\4`

Corresponding ephys: 
`AV024_2022-10-11_SparseNoise_part2_g0`

Issue: `flipperStEnIdx` gets partitioned into 3 with the 1 s flipper threshold even though this is one experiment

**Comment by cbimbo** [comment]
Arduino code is different (100Hz sampling and at each sample attributing a value, vs. taking the delays between flips as a Poisson distribution constrained between 10 and 200 ms). Need to change the arduino code.

**Comment by pipcoen** [comment]
Okay, this has been changed in the .txt and should work (I have tested at my computer). The flips should be less than 1s always. George will need to update the arduinos with the new code. I will add this to Clickup

**Comment by nippoo** [comment]
Would you mind submitting the new code as a pull request on https://github.com/nippoo/pipcb/blob/main/firmware/pip_control_board/pip_control_board.ino please? So I can make sure any new boards have the correct implementation!

**Comment by pipcoen** [comment]
Just needs to be tested. Have pushed to pipcp repo
