### ISSUE TITLE
Issues in autoRunOvernight

### ISSUE THREAD

**Issue by takacsflora** [cortex-lab/PinkRigs#29]
On kilo-1.
Some - to me - unexpected stuff is going on. 1) the matlabs don't remain open. 2) I think kilo-1 enters the email sending loop, when run overnight, but nothing beyond that (including kilosorting, alignments & ibl formatting). 

On kilo-2: 
I think the permssion errors might be related but several kilosortings start at the same time

**Comment by takacsflora** [comment]
Seems like Kilo-1 was suffering from overloaded 95% memory, restarting seems to fix some of that ....

**Comment by takacsflora** [comment]
@cbimbo  might you be able have a look at kilo-1 to confirm? My feeling is that the task scheduler does not always trigger the `nightmanager.bat` properly. But if you manually start `nightmanager.bat` it seems to work just fine,  all triggers seem to be enabled in task manager, and there is even a `Last Run Time` stamp, which seems to be correct. But no matlab is open and nothing beyond the training email is being processed unless manually prompted (I think...).

**Comment by takacsflora** [comment]
minor Update: I think the task scheduler app on this computer has some issue. (none of the tasks start, like google updates). I will loop in Dinu.

**Comment by cbimbo** [comment]
Matlab sessions were running but weren't visible. Switching the properties to 'Run only when user is logged on' worked (https://stackoverflow.com/questions/38847748/batch-file-via-task-scheduler-message-box-not-showing).
The 95% memory was because of all the sessions that accumulated without being displayed.
