### ISSUE TITLE
Inconsistencies in syntax between Matlab and Python with argument 'lastX'

### ISSUE THREAD

**Issue by cbimbo** [cortex-lab/PinkRigs#39]
When specifying which dates to load or process with argument 'lastX', the interpretation is different between Matlab and Python. In Matlab, it is the last X experiments (whatever their dates, e.g., in `csv.queryExp`) and in Python, it is the last X days (e.g., in `check_date_selection`**).

 ** btw, this function should be externalized, since it is now duplicated in the IBL format conversion script and the pyKS script.

**Comment by takacsflora** [comment]
function is externalised.

**Comment by takacsflora** [comment]
python `'lastX'` now matches the meaning of the matlab syntax. (last x days compared to today can also be called with the syntax `'previousXdays'`)
