### ISSUE TITLE
video alignment is weird 

### ISSUE THREAD

**Issue by takacsflora** [cortex-lab/PinkRigs#43]
```
subject = 'AV030'
expDate = '2022-12-05'
expNum= 2

cam = 'eyeCam'

camera.times are: 
 -9879.95262333,  -9877.9284865 ,  -9875.90434967, ...,
       354053.77659995, 354055.80073678, 354057.8248736
```

**Comment by cbimbo** [comment]
There was no IR dark flash in this experiment.
But the fact that it didn't error is not normal (it was finding by 'chance' two sync times, which usually doesn't happen). I now added a check that the number of frames makes sense...
