### ISSUE TITLE
Acute recordings not well handled in csv.checkForNewPinkRigRecordings

### ISSUE THREAD

**Issue by cbimbo** [cortex-lab/PinkRigs#47]
Currently reads the alignment file to get the expected number of probes. Should be independent. Also, throws probe mismatch.

**Comment by pipcoen** [comment]
This isn't great... but at the moment, if there is an "error" in the ephys, it will assume there are two probes... this causes some mismatches etc. with expected vs actual probe number, but only "warnings". Closing for now, since Acute isn't a major issue
