### ISSUE TITLE
Cannot request "all" dates with csv_queryExp.py

### ISSUE THREAD

**Issue by cbimbo** [cortex-lab/PinkRigs#50]
In the Python version of queryExp, it seems that requesting "all" dates (or "last...") crashes at l76. @takacsflora it may be due to recent changes -- could you please recheck? Thanks!
I get the error when running `stage_KS_queue(mouse_selection='EB014',date_selection='all',resort=False)`

**Comment by takacsflora** [comment]
Hi Celian,
Technically, 'all' was never implemented for stage_KS_queue, please use 'last600' for now, if you want to use this function. 
That being said, stage_KS_queue is only used for processing of newly acquired data, and for anything else, you can use pymanuals/manual_ephys.ipynb 
I can update/unify these codes down the line ofc.

**Comment by cbimbo** [comment]
Hi Flora. Thanks. FYI 'last600' doesn't work either (same line).

**Comment by takacsflora** [comment]
Hi Celian I cannot replicate this issue on kilo-2, calling `stage_KS_queue(mouse_selection='EB014',date_selection='last600',resort=False) `
works.
